### ISSUE TITLE
Cannot view requests after PR #134

### ISSUE THREAD

**Issue by jacob-g** [InternationalScratchWiki/scratch-confirmaccount-v3#136]
#134 caused a fatal exception whenever viewing a request. This has been rolled back on production, but needs to be investigated.

**Comment by ahmetlii** [comment]
Note: It also doesn't allow account requesting by the user and throws reference error.

**Comment by jacob-g** [comment]
Reproduced locally:
```
/wiki/Special:ConfirmAccounts/1 Error from line 102 of /var/www/html/w/extensions/scratch-confirmaccount-v3/src/RequestPage.php: Using $this when not in object context

Backtrace:

#0 /var/www/html/w/extensions/scratch-confirmaccount-v3/src/RequestPage.php(495): requestActionsForm(AccountRequest, string, boolean, OutputPage, SpecialConfirmAccounts, MediaWiki\Session\Session, string)
#1 /var/www/html/w/extensions/scratch-confirmaccount-v3/src/SpecialConfirmAccounts.php(416): requestPage(string, string, OutputPage, SpecialConfirmAccounts, MediaWiki\Session\Session, LanguageEn)
#2 /var/www/html/w/includes/specialpage/SpecialPage.php(600): SpecialConfirmAccounts->execute(string)
#3 /var/www/html/w/includes/specialpage/SpecialPageFactory.php(635): SpecialPage->run(string)
#4 /var/www/html/w/includes/MediaWiki.php(307): MediaWiki\SpecialPage\SpecialPageFactory->executePath(Title, RequestContext)
#5 /var/www/html/w/includes/MediaWiki.php(940): MediaWiki->performRequest()
#6 /var/www/html/w/includes/MediaWiki.php(543): MediaWiki->main()
#7 /var/www/html/w/index.php(53): MediaWiki->run()
#8 /var/www/html/w/index.php(46): wfIndexMain()
#9 {main}
```
